name: ReleaseCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/release.sh ${{secrets.AWS_BUCKET}} "myapp.zip" ${{secrets.AWS_ACCESS_KEY}} ${{secrets.AWS_SECRET_KEY}} "myapp.zip"